### ISSUE TITLE
对注册的疑问

### ISSUE THREAD

**Issue by ShengjieGeng** [smileCH/ComponentProject#1]
今天看到了您的对组件化的讲解，然后check。在mainactivity调用`ARouter.getInstance().build("/article/index").navigation();`启动article_module中的ArticalListActivity。愣是没找到在哪儿注册的ArticalListActivity路径path（/羞愧）。

**Comment by ShengjieGeng** [comment]
`arguments = [moduleName: project.getName()]`

**Comment by smileCH** [comment]
每太明白你的意思，demo中使用的是阿里开源的ARouter路由，如果对其使用不太熟悉的话可以去查看下官网文档，这是地址：https://github.com/alibaba/ARouter  希望能帮到你

**Comment by ShengjieGeng** [comment]
昨天看了ARouter，他们是用到注解来注册路径。一起看的路由模式是通过代码去注册的（嘿嘿）
