### ISSUE TITLE
代码混淆

### ISSUE THREAD

**Issue by wangcc0909** [smileCH/ComponentProject#2]
组件之间代码的混淆该如何处理呢?

**Comment by smileCH** [comment]
首先我觉得不应该在每一个业务组件中都开启代码混淆并配置混淆文件，很明显的一个弊端就是不便于统一管理。其实最终我们是在集成模式下进行打包然后发布的，所以我们应该在app壳工程中的build.gradle中开启混淆，以及配置混淆文件也应该放在app壳工程中
